
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tom-advisor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: 12345678
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  data:
    # redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      username:
#      password:
      lettuce:
        pool:
          # lettuce连接池最大连接数,默认8
          max-active: 8
          # lettuce连接池最大空闲连接数,默认0
          max-idle: 0
          # lettuce连接池最小空闲连接数,默认0
          min-idle: 0
          # lettuce连接池最大等待时间(单位毫秒),默认-1ms
          max-wait: -1ms
    # redisson配置
    redisson:
      enabled: true
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
server:
  port: 8282

sa-token:
  enabled: true
  excludes: /doLogin
